# Copyright (C) 2017 The Dagger Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description:
#   Tools for Dagger

package(default_visibility = ["//:src"])

java_library(
    name = "foo",
    srcs = ["Foo.java"],
    deps = ["//third_party:auto_service"],
)

java_library(
    name = "foo_with_dupe_file",
    srcs = ["Foo.java"],
    resources = ["dupe"],
    deps = ["//third_party:auto_service"],
)

java_library(
    name = "bar",
    srcs = ["Bar.java"],
    deps = ["//third_party:auto_service"],
)

java_library(
    name = "bar_with_dupe_file",
    srcs = ["Bar.java"],
    resources = ["dupe"],
    deps = ["//third_party:auto_service"],
)
